import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Two sidebars, because this site has two kinds of reader.
 *
 * `course` is the sequential path: someone working through the series, module
 * by module, alongside the videos.
 *
 * `reference` is the encyclopaedia: someone who arrived from a search engine
 * wanting one answer about one pattern. They should not have to work out which
 * module it was taught in.
 *
 * Pages are listed explicitly rather than autogenerated so that ordering is a
 * deliberate editorial choice.
 */
const sidebars: SidebarsConfig = {
  course: [
    'index',
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      items: [
        'start-here/how-to-use-this-repo',
        'start-here/setup',
        'start-here/learning-paths',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      collapsed: false,
      items: [
        'modules/index',
        'modules/01-foundations/index',
        'modules/02-reflection/index',
        'modules/03-tool-use/index',
        'modules/04-evaluation/index',
        'modules/05-planning-multi-agent/index',
        'modules/06-memory-context/index',
        'modules/07-mcp-integrations/index',
        'modules/08-observability-production/index',
        'modules/09-safety-security/index',
      ],
    },
    {
      type: 'category',
      label: 'Labs',
      // Rendered notebook pages are generated by tools/nb2md.py before the
      // build (see `make docs`), so they are listed here but not committed.
      items: ['labs/index', 'labs/01-foundations-01_first_agentic_workflow'],
    },
    {
      type: 'category',
      label: 'Projects',
      items: ['projects/index'],
    },
  ],

  reference: [
    {
      type: 'category',
      label: 'Foundations',
      collapsed: false,
      items: [
        'foundations/what-is-an-agent',
        'foundations/anatomy-of-an-agent',
        'foundations/autonomy-spectrum',
        'foundations/task-decomposition',
        'foundations/when-not-to-use-agents',
        'foundations/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Patterns',
      items: [
        'patterns/index',
        'patterns/prompt-chaining',
        'patterns/routing',
        'patterns/reflection',
        'patterns/tool-use',
        'patterns/react',
        'patterns/planning',
        'patterns/multi-agent',
        'patterns/human-in-the-loop',
      ],
    },
    {
      type: 'category',
      label: 'Building blocks',
      items: [
        'building-blocks/models',
        'building-blocks/prompting-for-agents',
        'building-blocks/tools-and-function-calling',
        'building-blocks/structured-outputs',
        'building-blocks/memory-and-state',
        'building-blocks/context-engineering',
        'building-blocks/retrieval-for-agents',
        'building-blocks/mcp',
      ],
    },
    {
      type: 'category',
      label: 'Evaluation',
      items: [
        'evaluation/eval-driven-development',
        'evaluation/error-analysis',
        'evaluation/component-vs-end-to-end',
        'evaluation/llm-as-judge',
        'evaluation/benchmarks',
      ],
    },
    {
      type: 'category',
      label: 'Production',
      items: [
        'production/architecture',
        'production/observability-and-tracing',
        'production/cost-and-latency',
        'production/reliability-and-retries',
        'production/deployment',
      ],
    },
    {
      type: 'category',
      label: 'Safety & security',
      items: [
        'safety/guardrails',
        'safety/prompt-injection',
        'safety/sandboxing-and-permissions',
        'safety/risk-framework',
      ],
    },
    {
      type: 'category',
      label: 'Frameworks',
      items: [
        'frameworks/index',
        'frameworks/no-framework',
        'frameworks/claude-agent-sdk',
        'frameworks/openai-agents-sdk',
        'frameworks/langgraph',
        'frameworks/comparison',
      ],
    },
    {
      type: 'category',
      label: 'References',
      items: [
        'references/reading-list',
        'references/papers',
        'references/attribution',
      ],
    },
  ],
};

export default sidebars;
